name: Sync SportsMonks Fixtures

on:
  workflow_dispatch:
  schedule:
    - cron: "17 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt
          
      - name: Sync Fixtures
        env:
          SPORTSMONKS_API_TOKEN: ${{ secrets.SPORTSMONKS_API_TOKENS }}
          WEBFLOW_API_TOKEN: ${{ secrets.WEBFLOW_API_TOKENS }}
        run: python sync.py 
