name: Sync SportsMonks Fixtures

on:
  workflow_dispatch:
  schedule:
    - cron: "17 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - name: Sync Fixtures
        env:
          SPORTSMONKS_API_TOKEN: ${{ secrets.OwEeRineBkybfvjhErbpLC9XPselqjFdGSkqJRa2Tg1dOwPAnc4kdXFtGE3O }}
          WEBFLOW_API_TOKEN: ${{ secrets.f02b9e2660c8cb1598211689ffdf102f3aeee1d8183c1cbe5089a8d36500a883 }}
        run: python sync.py

