name: Sync SportsMonks Fixtures

on:
  workflow_dispatch:
  schedule:
    - cron: "17 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - name: Check Sportmonks token
        env:
          SM_TOKEN: ${{ secrets.SPORTSMONKS_API_TOKEN }}
        run: |
          if [ -z "$SM_TOKEN" ]; then
            echo "SPORTSMONKS_API_TOKEN is EMPTY"
          exit 1
          fi

          echo "SPORTSMONKS_API_TOKEN exists"
          echo "Token length: ${#SM_TOKEN}"

      - name: Sync Fixtures
        env:
          SPORTSMONKS_API_TOKEN: ${{ secrets.SPORTSMONKS_API_TOKEN }}
          WEBFLOW_API_TOKEN: ${{ secrets.WEBFLOW_API_TOKEN }}
        run: python sync.py 
